# Generated by Django 4.2.2 on 2023-07-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128)),
                ('start_bid', models.IntegerField()),
                ('image', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=32)),
            ],
        ),
    ]
