# Generated by Django 4.2.2 on 2023-08-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='highest_bid',
            field=models.IntegerField(default=0),
        ),
    ]
