# Generated by Django 4.2.2 on 2023-08-01 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings_highest_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='highest_bid_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
