# Generated by Django 4.2.2 on 2023-08-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='description',
            field=models.CharField(max_length=512),
        ),
    ]
