# Generated by Django 4.2.2 on 2023-08-02 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listings_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='highest_bid_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
