# Generated by Django 4.2.2 on 2023-08-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listings_highest_bid_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='end_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
